In [726]:
import numpy as np
from sklearn import datasets

In [727]:
# сгеренируем датасет 
X, y = datasets.make_classification(n_samples=100, n_features=4, n_informative=2,
                                    n_redundant=0, n_classes=2, random_state=1)

In [728]:
def sigmoid(z):
    res = 1 / (1 + np.exp(-z))
    return res

**Задание 1*** Измените функцию calc_logloss так, чтобы нули по возможности не попадали в np.log.

In [729]:
#поставим дополнительные верхние и нижние ограничения для предсказываемых значений близкие к 1 и к 0 соответственно

def calc_logloss(y, y_pred):
    y_pred = y_pred.astype(float) #переведем в формат float и заменим значения на близкие к ним
    for i, n in enumerate(y_pred):
        if n == 1:
            y_pred[i]=0.99999
        elif n == 0:
            y_pred[i]=0.00001
    err = - np.mean(y * np.log(y_pred) + (1.0 - y) * np.log(1.0 - y_pred))
    return err

In [730]:
y1 = np.array([1, 0])
y_pred1 = np.array([1, 1])


calc_logloss(y1, y_pred1)

5.75646773251239

**Задание 2.** Подберите аргументы функции eval_model для логистической регрессии таким образом, чтобы log loss был минимальным.


In [731]:
def eval_model(X, y, iterations, eta=1e-4):
    np.random.seed(42)
    W = np.random.randn(X.shape[1])
    n = X.shape[0]
    
    for i in range(iterations):
        z = np.dot(X, W)
        y_pred = sigmoid(z)
        err = calc_logloss(y, y_pred)
        
        dQ = 1/n * X.T @ (y_pred - y)
        W -= eta * dQ
        if i % (iterations / 10) == 0:
            print(f'Iteration: {i}, Weights: {W}, Error: {err}')
    return W

In [732]:
W = eval_model(X, y, iterations= 5000, eta=5e-1)
W

Iteration: 0, Weights: [ 0.49395269 -0.12861884  0.59236705  1.60232867], Error: 0.2839757862862511
Iteration: 500, Weights: [ 1.20231792  0.42084834 -0.61841978  5.21690257], Error: 0.09061263152129193
Iteration: 1000, Weights: [ 1.44869861  0.54190995 -0.80810902  5.89065942], Error: 0.08823059421456916
Iteration: 1500, Weights: [ 1.57124945  0.60242104 -0.90464995  6.23859814], Error: 0.08761705713607278
Iteration: 2000, Weights: [ 1.64227624  0.63750691 -0.96129163  6.44408142], Error: 0.08740576474734783
Iteration: 2500, Weights: [ 1.68625983  0.65922832 -0.99662388  6.57270506], Error: 0.08732349624239091
Iteration: 3000, Weights: [ 1.71447487  0.67315833 -1.01939324  6.6557635 ], Error: 0.08728931380716133
Iteration: 3500, Weights: [ 1.73295366  0.68227941 -1.03434975  6.71039088], Error: 0.08727455986602291
Iteration: 4000, Weights: [ 1.74521251  0.68832937 -1.04429128  6.74673078], Error: 0.0872680397703641
Iteration: 4500, Weights: [ 1.75341231  0.69237567 -1.05094968  6.7710

array([ 1.75891766,  0.69509215, -1.05542402,  6.78745216])

**Задание 3.** Создайте функцию calc_pred_proba, возвращающую предсказанную вероятность класса 1 (на вход подаются W, который уже посчитан функцией eval_model и X, на выходе - массив y_pred_proba).


In [733]:
def calc_pred_proba(W, X):
    z = np.dot(X, W)
    y_pred_proba = sigmoid(z)
    
    return y_pred_proba

In [734]:
calc_pred_proba(W, X)

array([6.40515487e-05, 1.81672444e-01, 7.12518377e-04, 1.25548188e-03,
       8.29467561e-05, 9.62725675e-01, 9.99880070e-01, 9.98295797e-01,
       9.96988336e-01, 8.87534075e-01, 9.97685609e-01, 2.56822853e-02,
       5.86363903e-04, 9.63149594e-01, 5.32933358e-04, 3.61746198e-04,
       9.99766906e-01, 1.24502149e-05, 1.53359328e-03, 9.99999776e-01,
       4.68610122e-03, 1.28331205e-04, 4.66367878e-03, 9.99980927e-01,
       9.79658953e-01, 9.99182922e-01, 6.49472917e-01, 9.99839634e-01,
       1.27484581e-01, 4.06283001e-03, 1.55147643e-05, 9.23409976e-01,
       9.99997640e-01, 7.68445049e-05, 1.92700247e-05, 9.70385559e-06,
       9.98646642e-01, 9.99472797e-01, 3.39263185e-03, 7.37476582e-05,
       8.82824252e-05, 9.99994721e-01, 9.99811089e-01, 9.13628602e-01,
       1.03915771e-03, 1.12361884e-03, 9.69491748e-01, 2.99403612e-04,
       9.96675635e-01, 1.43084634e-03, 8.57538589e-01, 9.98482707e-01,
       9.99741725e-01, 7.78795031e-01, 9.99938988e-01, 9.99946587e-01,
      

**Задание 4.** Создайте функцию calc_pred, возвращающую предсказанный класс (на вход подаются W, который уже посчитан функцией eval_model и X, на выходе - массив y_pred).

In [735]:
y_pred_list = np.array([])
np.append(y_pred_list, 1)
np.append(y_pred_list, 0)

array([0.])

In [736]:
def calc_pred(W, X):
    y_pred_list = []
    z = np.dot(X, W)
    y_pred_proba = sigmoid(z)
    for i in y_pred_proba:
        if i >=0.5:
            y_pred_list.append(1)
        elif i < 0.5:
            y_pred_list.append(0)
        elif i > 1 or i <0:
            print('Error!')
        y_pred = np.array(y_pred_list)
    return y_pred


In [737]:
#Еще один вариант реализации с указанием дополнительного параметра threshold
'''
def calc_pred(W, X, threshold):
    y_pred_list = []
    z = np.dot(X, W)
    y_pred_proba = sigmoid(z)
    for i in y_pred_proba:
        if i >=(threshold):
            y_pred = 1
        elif i < (threshold):
            y_pred = 0
        elif i > 1 or i <0 or threshold > 1 or threshold < 0:
            print('Error!')
        y_pred_list.append(y_pred)
    return y_pred_list
    
    '''

"\ndef calc_pred(W, X, threshold):\n    y_pred_list = []\n    z = np.dot(X, W)\n    y_pred_proba = sigmoid(z)\n    for i in y_pred_proba:\n        if i >=(threshold):\n            y_pred = 1\n        elif i < (threshold):\n            y_pred = 0\n        elif i > 1 or i <0 or threshold > 1 or threshold < 0:\n            print('Error!')\n        y_pred_list.append(y_pred)\n    return y_pred_list\n    \n    "

In [738]:
calc_pred(W, X)

array([0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1,
       0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1])

**Задание 5*.** Реализуйте функции для подсчета Accuracy, матрицы ошибок, точности и полноты, а также F1 score.

In [739]:
y_true = np.array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])
y_pred = np.array([1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1])

In [740]:
def find_metrics(y_true, y_pred):
    
    # Создадим матрицу ошибок
    conf_matrix = np.zeros([2,2])

    # определим TP, FP, FN, TN
    conf_matrix[0, 0] = TP = ((y_true == 1) & (y_pred == 1)).sum()
    conf_matrix[0, 1] = FP = ((y_true == 0) & (y_pred == 1)).sum()
    conf_matrix[1, 0] = FN = ((y_true == 1) & (y_pred == 0)).sum()
    conf_matrix[1, 1] = TN = ((y_true == 0) & (y_pred == 0)).sum()
    
    # Рассчитаем метрики
    acc = (TP+TN)/(TP+FP+FN+TN)
    prec_0 = TP/(TP+FP)
    prec_1 = FP/(TP+FP)
    macroavg_prec = (prec_0+prec_1)/2
    weigh_prec = ((y_pred == 0).sum()/len(y_pred)*prec_0) + ((y_pred == 1).sum()/len(y_pred)*prec_1)
    
    
    rec_0 = TP/(TP+FN)
    rec_1 = FP/(FP+TN)
    macroavg_rec = (rec_0 + rec_1)/2
    weigh_rec = ((y_pred == 0).sum()/len(y_pred)*rec_0) + ((y_pred == 1).sum()/len(y_pred)*rec_1)
    
    f1_0 = prec_0*rec_0/(prec_0+rec_0)
    f1_1 = prec_1*rec_1/(prec_1+rec_1)
    macroavg_f1 = (f1_0 + f1_1)/2
    weigh_f1 = ((y_pred == 0).sum()/len(y_pred)*f1_0) + ((y_pred == 0).sum()/len(y_pred)*f1_1)
    
    # Выведем результат
    print(f'Confusion_matrix:\n{conf_matrix}'
          f'accuracy: {acc} \n\npresicion_0 class: {prec_0} \npresicion 1 class: {prec_1}'
          f'\n\nmacroavg_presicion: {macroavg_prec} \nweighted_precision: {weigh_prec}'
          f' \n\nrecall 0 class: {rec_0} \nrecall 1 class: {rec_1}, \n\nmacroavg_recall: {macroavg_rec} \nweighted_recall: {weigh_rec}'
          f'\n\nf1_score 0 class: {f1_0} \nf1_score 1 class: {f1_1:.2f} \n\nmacroavg_f1_score: {macroavg_f1} \nweighted_f1_score: {weigh_f1}')
    

In [741]:
find_metrics(y_true, y_pred)

Confusion_matrix:
[[6. 4.]
 [4. 6.]]accuracy: 0.6 

presicion_0 class: 0.6 
presicion 1 class: 0.4

macroavg_presicion: 0.5 
weighted_precision: 0.5 

recall 0 class: 0.6 
recall 1 class: 0.4, 

macroavg_recall: 0.5 
weighted_recall: 0.5

f1_score 0 class: 0.3 
f1_score 1 class: 0.20 

macroavg_f1_score: 0.25 
weighted_f1_score: 0.25


**Задание 6.** Могла ли модель переобучиться? Почему?

Да, как и в случае линейной регрессии, разделяющая линия на обучающем датасете может слишком точно подстроиться под объекты и запомнить их расположение и тогда не сможет выдать хорошее предсказание на тесте